//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.6.3
//     from Assets/Scripts/InputAction/JoystickControl.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @JoystickControl: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @JoystickControl()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""JoystickControl"",
    ""maps"": [
        {
            ""name"": ""TurnBasedCombat"",
            ""id"": ""2cd9bf3a-5a26-4afc-950e-9bb200d47b8f"",
            ""actions"": [
                {
                    ""name"": ""ScrollOrSelect"",
                    ""type"": ""Value"",
                    ""id"": ""1faee7ba-e36d-4bc5-ac4d-96b04e485edc"",
                    ""expectedControlType"": ""Stick"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Confirm"",
                    ""type"": ""Button"",
                    ""id"": ""2fdd2cc5-5d8f-4674-94ab-c8ac406ca12c"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""8e7c2288-0561-4f69-923f-b11a5a1b9c13"",
                    ""path"": ""<Gamepad>/leftStick"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ScrollOrSelect"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""0c7a45a6-da49-44da-a389-195d79f68dbc"",
                    ""path"": ""<Gamepad>/buttonEast"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Confirm"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // TurnBasedCombat
        m_TurnBasedCombat = asset.FindActionMap("TurnBasedCombat", throwIfNotFound: true);
        m_TurnBasedCombat_ScrollOrSelect = m_TurnBasedCombat.FindAction("ScrollOrSelect", throwIfNotFound: true);
        m_TurnBasedCombat_Confirm = m_TurnBasedCombat.FindAction("Confirm", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // TurnBasedCombat
    private readonly InputActionMap m_TurnBasedCombat;
    private List<ITurnBasedCombatActions> m_TurnBasedCombatActionsCallbackInterfaces = new List<ITurnBasedCombatActions>();
    private readonly InputAction m_TurnBasedCombat_ScrollOrSelect;
    private readonly InputAction m_TurnBasedCombat_Confirm;
    public struct TurnBasedCombatActions
    {
        private @JoystickControl m_Wrapper;
        public TurnBasedCombatActions(@JoystickControl wrapper) { m_Wrapper = wrapper; }
        public InputAction @ScrollOrSelect => m_Wrapper.m_TurnBasedCombat_ScrollOrSelect;
        public InputAction @Confirm => m_Wrapper.m_TurnBasedCombat_Confirm;
        public InputActionMap Get() { return m_Wrapper.m_TurnBasedCombat; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(TurnBasedCombatActions set) { return set.Get(); }
        public void AddCallbacks(ITurnBasedCombatActions instance)
        {
            if (instance == null || m_Wrapper.m_TurnBasedCombatActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_TurnBasedCombatActionsCallbackInterfaces.Add(instance);
            @ScrollOrSelect.started += instance.OnScrollOrSelect;
            @ScrollOrSelect.performed += instance.OnScrollOrSelect;
            @ScrollOrSelect.canceled += instance.OnScrollOrSelect;
            @Confirm.started += instance.OnConfirm;
            @Confirm.performed += instance.OnConfirm;
            @Confirm.canceled += instance.OnConfirm;
        }

        private void UnregisterCallbacks(ITurnBasedCombatActions instance)
        {
            @ScrollOrSelect.started -= instance.OnScrollOrSelect;
            @ScrollOrSelect.performed -= instance.OnScrollOrSelect;
            @ScrollOrSelect.canceled -= instance.OnScrollOrSelect;
            @Confirm.started -= instance.OnConfirm;
            @Confirm.performed -= instance.OnConfirm;
            @Confirm.canceled -= instance.OnConfirm;
        }

        public void RemoveCallbacks(ITurnBasedCombatActions instance)
        {
            if (m_Wrapper.m_TurnBasedCombatActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(ITurnBasedCombatActions instance)
        {
            foreach (var item in m_Wrapper.m_TurnBasedCombatActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_TurnBasedCombatActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public TurnBasedCombatActions @TurnBasedCombat => new TurnBasedCombatActions(this);
    public interface ITurnBasedCombatActions
    {
        void OnScrollOrSelect(InputAction.CallbackContext context);
        void OnConfirm(InputAction.CallbackContext context);
    }
}
